config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :usuarios, as: :users,only: [:show,:update]
  resources :friendships, only: [:create,:update,:index]

  devise_for :users, controllers:{
  	omniauth_callbacks: "users/omniauth_callbacks"
  }


  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up" 

  authenticated :user do
    root 'main#home'
  end

  unauthenticated :user do
    root 'main#unregistered'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
	before_action :set_user
	before_action :authenticate_user!,only: [:update]
	before_action :authenticate_owner!,only: [:update]	

	def show
		@are_friends = current_user.my_friend?(@user)
	end

	def update
		respond_to do |format|
			if @user.update(user_params)
				format.html{ redirect_to @user}
				format.json{ render :show, status: :created, location: @user }
				format.js
			else
				format.html{redirect_to @user,notice:@user.errors.full_messages}
				format.json{ render json: @user.errors }
			end
		end
	end

	private
		def set_user
			@user = User.find(params[:id])
		end

		def authenticate_owner!
			if current_user != @user
				redirect_to root_path, notice: "No estás autorizado",status: :unauthorized
			end
		end

		def user_params
			params.require(:user).permit(:email,:username,:name,:last_name,:bio,:avatar,:cover)
		end
end

app/views/usuarios/_menu_avatar.haml
.absolute{style:"top:10px;right:10px;"}
	%button.mdl-button.white-text.mdl-js-button.mdl-button--icon#user-menu-avatar-left
		%i.material-icons more_vert
	%ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect{for:"user-menu-avatar-left"}
		%li.mdl-menu__item.file-activate{for:"#user_avatar"} Actualizar avatar
		%li.mdl-menu__item.file-activate{for:"#user_cover"} Actualizar cover

app/views/usuarios/show.haml
.row.center-xs
	=grid xs:10,sm:8,md:6,lg:4 do
		.white.mdl-shadow--2dp.top-space.relative
			.big-padding.white-text.text-left.cover.relative#user-cover{style:"background-image:url(#{@user.cover.url(:medium)})"}
				=render "usuarios/menu_avatar"
				.top-space#user-avatar
					=circle_img @user.avatar.url(:medium),100
						
			%section.border-bottom.top-space
				.row.middle-xs
					=grid class:"col-xs" do
						%h1.no-margin.medium
							%span= best_in_place_if current_user == @user,@user, :name
							%span= best_in_place_if current_user == @user,@user, :last_name		
						%p
							%span= best_in_place_if current_user == @user,@user, :username		
					=grid xs:4,sm:2 do
						-unless @are_friends
							=button_to friendships_path(friend_id: @user.id),method: :post, remote: true, :"data-type" => "script", class:"mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect" do
								%i.material-icons person_add
			.large-padding
				.row
					=grid class:"col-xs" do
						Seguidores
					=grid class:"col-xs" do
						=@user.posts.count
						Posts
				.row.center-xs
					=grid xs:8,md:10 do
						%span= best_in_place_if current_user == @user,@user, :bio

			.top-space
				=form_for @user,remote: true do |f|
					=f.file_field :avatar,class:"remotipart"
				=form_for @user, remote: true do |f|
					=f.file_field :cover,class:"remotipart"
					